### ISSUE TITLE
No catalogue items message off centred when loading/using cached results

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#180]

**Comment by joshuadkitenge** [comment]
![categoryItemsTableFormattingChange](https://github.com/ral-facilities/inventory-management-system/assets/90245114/5e3ee93f-3b48-4779-81f1-494c77c2954c)
Not sure why but the position of the no results text changes when the error is shown.

_Originally posted by @joelvdavies in https://github.com/ral-facilities/inventory-management-system/pull/177#discussion_r1422594143_

**Comment by joelvdavies** [comment]
Another alternative I just found is using a custom component to force it to the center e.g.
```
    renderEmptyRowsFallback: (props) => {
      return (
        <Box justifyContent="center" alignItems="center" textAlign="center">
          {noResultsTxt}
        </Box>
      );
    },
```
The styling would need some slight adjusting though, e.g. the text colour would probably need to be  text.secondary to get the lighter grey.

**Comment by joelvdavies** [comment]
We managed to trace it to `enableTopToolbar: false` - A value of undefined defaults to true which works fine, but with a value of false it breaks. The above comment can fix it partially however while loading the message reverts back to the default component with the same issue so its not a suitable solution. The catalogueCategoryTableView is fine, even though it too has a value of false. Ultimately it appears to be due to this line in MRT https://github.com/KevinVandy/material-react-table/blob/e6531fcd287fae2d4e39aba930be256a3a75453a/packages/material-react-table/src/body/MRT_TableBody.tsx#L260.

**Comment by joshuadkitenge** [comment]
not an issue anymore as we use TopToolbar in all tables

**Comment by joelvdavies** [comment]
@joshuadkitenge It's still in the dense items table or is that fixed as well now?

**Comment by joshuadkitenge** [comment]
The items dense table isn't used anywhere. The dense view was meant to be use for the items table in systems. I don't think it worth removing. I know another feature I can use this view for later.

**Comment by joelvdavies** [comment]
> The items dense table isn't used anywhere. The dense view was meant to be use for the items table in systems. I don't think it worth removing. I know another feature I can use this view for later.

Sure as long as we don't forget about this if we use it again. It may be fixed by MRT at some point and then we can be sure.
