### ISSUE TITLE
Scigateway refresh issue 

### ISSUE THREAD

**Issue by joshuadkitenge** [ral-facilities/inventory-management-system#399]
![refresh issue](https://github.com/ral-facilities/inventory-management-system/assets/83226114/86cb4f3f-1048-4b76-b8ad-de7abc386fa4)

**Comment by joelvdavies** [comment]
After investigating this is caused by the redirect only occurring after loading the page first. Then when logging in again the failed request is not retried causing an infinite load. Ideally access would be prevented on SciGateway's side but with the way it currently functions doing this based on whether the plugin is authorised or not would cause the homepage to be inaccessible effecting other plugins like datagateway. So for now it seems best to deal with this on IMS e.g. https://github.com/ral-facilities/datagateway/pull/839/files#diff-fb403615f446145706c61b52120b1f6f1351d9cacf71b31c590299af9ed90336. By redirecting to login when accessing a page that isn't the homepage.
