### ISSUE TITLE
Investigate using router provider for some error handling

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/inventory-management-system#459]
https://reactrouter.com/en/main/start/tutorial#handling-not-found-errors allows us to have 404 pages for invalid ids, and more general error pages for 500 we could look at implementing. Could conflict with the style of SciGateway 404 pages.

**Comment by MatteoGuarnaccia5** [comment]
The only implementation possible means that we would not be able to use react query, its either one or the other which then makes it pointless to implement. A method was using the `loader` function in our router paths but...

'The `loader` function is designed to be synchronous and fetch data before the component renders. You can fetch data using standard async  TypeScript (like fetch) instead of using React hooks. However, this would work best if you're able to fetch the data outside of the React lifecycle.'
